### ISSUE TITLE
Playing back User's custom animation USDZ

### ISSUE THREAD

**Issue by enzyme69** [maxxfrazer/RealityKit-CardFlip#1]
Hi Max, do you have any tips on how to playback user custom animation (character animation, USDZ, originally from Mixamo).

I tried something like below and not working somewhat.

```
            //monkey.availableAnimations
            
            //AnimationResource.
            
            let anim = monkey.availableAnimations
            // animation name = "Armature|mixamo.com|Layer0|"
            
            //monkey.playAnimation(anim[0], transitionDuration: 0.5, startsPaused: false)
            
            //monkey.playAnimation(anim[0], transitionDuration: 2.5, startsPaused: true)

            monkey.playAnimation(anim[0])
            
            monkey.playAnimation(named: "Armature|mixamo.com|Layer0|") // weird that this does not work.
```
            
So far, the easiest way is perhaps to load entity that's already assigned animation via Reality Composer.

**Comment by maxxfrazer** [comment]
I’m afraid I’m yet to try out using USDZ animations, so am not able to help you with this issue at this time.
There may be someone who knows how to get your issue working on the [Apple Forums](https://forums.developer.apple.com/community/graphics-and-games/realitykit-and-reality-composer/content)
