### ISSUE TITLE
Anchoring and position of spawned Entity

### ISSUE THREAD

**Issue by enzyme69** [maxxfrazer/RealityKit-CardFlip#2]
Based on your Class example of Entity, I made something like this:

```swift
//
//  ViewController.swift
//  ARClassExample
//
//  Created by JIMMY GUNAWAN on 17/8/19.
//  Copyright © 2019 JIMMY GUNAWAN. All rights reserved.
//

import UIKit
import RealityKit




class ViewController: UIViewController {
    
    @IBOutlet var arView: ARView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Load the "Box" scene from the "Experience" Reality File
        let boxAnchor = try! Experience.loadBox()
        
        // Add the box anchor to the scene
        arView.scene.anchors.append(boxAnchor)
        
        // example Class CustomBox
        // maxxfrazer
        class CustomBox: Entity, HasModel {
          required init(color: UIColor) {
            super.init()
            self.components[ModelComponent] = ModelComponent(
                mesh: .generateBox(size: [0.01, 0.02, 0.011]),
              materials: [SimpleMaterial(
                color: color,
                isMetallic: false)
              ]
            )
          }
            
            required init() {
                fatalError("init() has not been implemented")
            }
        }
        
        let boxA = CustomBox(color: UIColor.red)
        boxA.position = SIMD3(0.0, 0.1, 0.0)
        
        let boxB = CustomBox(color: UIColor.green)
        boxB.position = SIMD3(0.0, 0.2, 0.0)
        
        let boxC = CustomBox(color: UIColor.blue)
        boxC.position = SIMD3(0.0, 0.3, 0.0)
        
        boxAnchor.addChild(boxA)
        boxAnchor.addChild(boxB)
        boxAnchor.addChild(boxC)


        
    }
}

```

I am however surprised by how the Entity being created procedurally is positioned in the "wrong place". I thought I use the boxAnchor (default AR template) and was hoping the entities placed at zero zero zero world axis.

**Comment by maxxfrazer** [comment]
Based on your code I can’t see specifically why they wouldn’t be placed on top of each other on the y axis. Could you add a screenshot of your problem?

Also GitHub issues isn’t typically the best place for general Q&A; I’d recommend leaving a response on Medium or a message on Twitter in the future

**Comment by maxxfrazer** [comment]
It would seem that loading the box from the Experience might be redundant also; would an AnchorEntity not be good enough or do you need the geometry for the cube?

**Comment by enzyme69** [comment]
I load the box from experience, just in case I want to replace it visually from RC.

But the issue was that the stacking of boxes are in different places, randomly, which is strange because I specify an anchor clearly but when the app runs and AR running, the position changes.

I will come back to this... I might use Twitter. Medium is not working for me, only 10 views per week.

**Comment by maxxfrazer** [comment]
If you post a picture response that would really help out, I can imagine exactly what this should look like, but it could be different from what you're expecting.

Let me know these 2 things in order for me to help out:
What should this look like, and what does it look like (ideally both with images)

**Comment by maxxfrazer** [comment]
I'm going to close this issue as there isn't enough information to move forward with helping you out unfortunately
